name: "Orangefox Recovery"
description: "Building OrangeFox Recovery Using Github Action"
author: "AnGgIt86"

branding:
  icon: 'terminal'
  color: 'gray-dark"'

inputs:
  FOX_SYNC:
    description: "Source On OrangeFox Recovery"
    required: false
    default: "https://gitlab.com/OrangeFox/sync.git"
  FOX_SYNC_BRANCH:
    description: "Branch On Orangefox For Sync"
    required: true
    default: "12.1"
  KERNEL_TREE:
    description: 'Kernel Tree On Your Device'
    required: false
    default: ''
  KERNEL_BRANCH:
    description: 'Branch On Your Kernel Tree'
    required: false
    default: ''
  KERNEL_PATH:
    description: 'Path On Your Kernel Directory'
    required: false
    default: 'kernel/vivo/1938'
  DEVICE_TREE:
    description: 'OrangeFox Device Tree'
    required: true
    default: 'https://github.com/UntuKemeng/ORF_device_vivo_1938'
  DEVICE_TREE_BRANCH:
    description: 'OrangeFox Device Tree Branch'
    required: true
    default: '12.1'
  DEVICE_PATH:
    description: 'Specify Your Device Path'
    required: true
    default: 'device/vivo/1938'
  DEVICE_NAME:
    description: 'Specify Your Device Codename'
    required: true
    default: '1938'
  BUILD_TARGET:
    description: 'Specify Your Build Target [boot, recovery, vendorboot'
    required: true
    default: 'recovery'
  COMMON_TREE:
    description: 'Common Tree On Your Device'
    required: false
    default: ''
  COMMON_BRANCH:
    description: 'Branch On Your Common Tree'
    required: false
    default: ''
  COMMON_PATH:
    description: 'Path On Your Common Directory'
    required: false
    default: 'common/vivo/1938'
  TG_CHAT_ID:
    description: 'Telegram Chat ID'
    required: false
    default: ''
  TG_TOKEN:
    description: 'Telegram Bot Token'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:

    - name: 🗑️ Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: 💽 Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 20

    - name: 🏢 Build Environment
      shell: bash
      run: |
        sudo apt install aria2 -y
        git clone https://github.com/akhilnarang/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh

    - name: 🎡 Set-up Manifest Sync
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
      run: |
        source config.sh
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox && cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone ${{ inputs.FOX_SYNC }} && cd sync
        ./orangefox_sync.sh --branch ${{ inputs.FOX_SYNC_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        cp -r ${GITHUB_WORKSPACE}/maintainer.png ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/bootable/recovery/gui/theme/portrait_hdpi/images/Default/About
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
        if [[ ! -d bootable/recovery/gui/theme ]]; then
            git clone https://gitlab.com/OrangeFox/misc/theme.git bootable/recovery/gui/theme || { echo "ERROR: Failed to Clone the OrangeFox Theme!" && exit 1; }
        fi
        if [[ ! -z "${{ inputs.KERNEL_TREE }}" ]]; then
            git clone ${{ inputs.KERNEL_TREE }} -b ${{ inputs.KERNEL_BRANCH }} ${{ inputs.KERNEL_PATH }}
        fi
        if [[ ! -z "${{ inputs.COMMON_TREE }}" ]]; then
            git clone ${{ inputs.COMMON_TREE }} -b ${{ inputs.COMMON_BRANCH }} ${{ inputs.COMMON_PATH }}
        fi

    - name: 🦊 Building OrangeFox
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
      run: |
        source config.sh
        timeStart
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        export LC_ALL="C"
        BUILDLOG="${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/build.log"
        build_message "Prepare for build..."
        set +e
        . build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        build_message "lunch twrp_${{ inputs.DEVICE_NAME }}-eng"
        lunch twrp_${{ inputs.DEVICE_NAME }}-engmake
        mkfifo reading
        tee "${BUILDLOG}" < reading &
        build_message "Staring bro...🔥"
        sleep 2
        build_message "🛠️ Building..."
        progress |& mka adbd ${{ inputs.BUILD_TARGET }}image -j$(nproc --all) > reading || { echo "ERROR: Failed to Build OrangeFox!" && exit 1; }
        retVal=$?
        timeEnd
        statusBuild

    - name: 📝 Set Release Properties
      shell: bash
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Jakarta date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}

    - name: 📤 Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## OrangeFox Recovery Build - Unofficial
          Build: fox_${{ inputs.FOX_SYNC_BRANCH }}
          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
